# Generated by Django 4.2.1 on 2025-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
