# Generated by Django 4.2.1 on 2025-08-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_slug_alter_sellerproductprice_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sellerproductprice',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='product_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prdct_comments', to='products.product', verbose_name='Product'),
        ),
    ]
