# Generated by Django 4.2.1 on 2025-02-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoptions',
            old_name='product_id',
            new_name='product',
        ),
    ]
