# Generated by Django 4.2.1 on 2025-08-04 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_id_image_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prdct_comments', to='products.product', verbose_name='Product'),
        ),
    ]
