# Generated by Django 4.2.1 on 2025-12-01 10:57
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproductprice',
            name='discount',
            field=models.PositiveIntegerField(default=100, verbose_name='Discount'),
        ),
    ]
