# Generated by Django 4.2.1 on 2025-12-01 10:59
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_sellerproductprice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductprice',
            name='discount',
            field=models.PositiveIntegerField(default=100, verbose_name='Discount'),
        ),
    ]
