# Generated by Django 4.2.1 on 2026-02-22 04:12

from django.conf import settings
from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_alter_sellerproductprice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_prdct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[products.validators.validate_rate], verbose_name='Rate'),
        ),
    ]
